server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id : payment_routh #payment_route  # 路由的id，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-SERVICE  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  #断言，路由匹配的进行路由

        - id: payment_routh2 #payment_route # 路由的id，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001
          uri: lb://CLOUD-PROVIDER-SERVICE  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**  #断言，路由匹配的进行路由
            - After=2022-07-07T16:43:53.350+08:00[Asia/Shanghai]
            #- cookie=username,zzyy


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    # 表示是否将自己注册到Eureka默认true
    register-with-eureka: true
    # 是否从Eureka抓取已有注册信息，默认true，单节点无所谓，集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 集群版
     # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      # 单机版
      defaultZone: http://localhost:7001/eureka